### ISSUE TITLE
[BUG]VertexAI Plugin is broken in Cloud.

### ISSUE THREAD

**Issue by Sanuki-073** [langgenius/dify#16472]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.1.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

After installing the VertexAI plugin (version 0.0.8) from the marketplace and configuring Vertex AI in the model provider, an error occurred stating that the module 'google.cloud.aiplatform_v1' has no attribute 'GenerativeModel'. 

Additionally, when installing version 0.0.7, although normal conversations work, the agent becomes unusable due to the following error: Run failed: Failed to transform agent message: PluginInvokeError: {"args":{},"error_type":"Exception","message":"read llm model failed: request failed: [vertex_ai] Error: PluginInvokeError: {\"args\":{\"description\":\"[models] Error: module 'vertexai.generative_models' has no attribute 'Schema'\"},\"error_type\":\"InvokeError\",\"message\":\"[models] Error: module 'vertexai.generative_models' has no attribute 'Schema'\"}"}

### ✔️ Expected Behavior

The system should operate without errors, allowing normal conversations and proper agent functionality without encountering issues such as missing attributes like 'GenerativeModel' or 'Schema'.

### ❌ Actual Behavior

version: 0.0.8:
  Could not set up VertexAI.
  Error message is "module 'google.cloud.aiplatform_v1' has no attribute 'GenerativeModel'. "
version: 0.0.7:
  Could not use Gemini 2.0 flash in Agent.
  Error message is "Run failed: Failed to transform agent message: PluginInvokeError: {"args":{},"error_type":"Exception","message":"read llm model failed: request failed: [vertex_ai] Error: PluginInvokeError: {"args":{"description":"[models] Error: module 'vertexai.generative_models' has no attribute 'Schema'"},"error_type":"InvokeError","message":"[models] Error: module 'vertexai.generative_models' has no attribute 'Schema'"}"}"
version: 0.0.6:
  is same as 0.0.7.

**Comment by Sanuki-073** [comment]
It seems that this change is a major mistake...
[dify-plugin's pull request : version 0.0.8 of vertex ai](https://github.com/langgenius/dify-official-plugins/pull/500)

**Comment by crazywoola** [comment]
I noticed that you used 0.0.6 and 0.0.7, they both have some problems right?

**Comment by Sanuki-073** [comment]
@crazywoola 
>I noticed that you used 0.0.6 and 0.0.7, they both have some problems right?

Yes.
If I use version 0.0.7, I got a error messages in Agent block:
Run failed: Failed to transform agent message: PluginInvokeError: {"args":{},"error_type":"Exception","message":"read llm model failed: request failed: [vertex_ai] Error: PluginInvokeError: {"args":{"description":"[models] Error: module 'vertexai.generative_models' has no attribute 'Schema'"},"error_type":"InvokeError","message":"[models] Error: module 'vertexai.generative_models' has no attribute 'Schema'"}"}

<img width="1462" alt="Image" src="https://github.com/user-attachments/assets/66fe7e93-90b0-4c8a-b9f2-1c2125d9dd91" />

**Comment by Sanuki-073** [comment]
@kangjianhua 
This probably isn't an issue with Dify's version, but rather a bug in the VertexAI plugin version 0.0.8.
If it's just a simple chat (not involving usage within Tool or Agent blocks), version 0.0.7 should work.

**Comment by david-sabata** [comment]
I'm having the same issue on a self-hosted instance. I cannot even configure the plugin. The version is `0.0.8`

```json
{
    "code": "invalid_param",
    "message": "module 'google.cloud.aiplatform_v1' has no attribute 'GenerativeModel'",
    "status": 400
}
```

**Comment by abbottdev** [comment]
also just ran into this with the following logs:
```
e9d-4bc7-44c5-8923-0367ea63debf/dispatch/llm/invoke"
2025-03-25 16:24:01 api-1            | 2025-03-25 16:24:01.475 DEBUG [Thread-1491 (_generate_worker)] [connectionpool.py:544] - http://plugin_daemon:5002 "POST /plugin/f808fe9d-4bc7-44c5-8923-0367ea63debf/dispatch/llm/invoke HTTP/1.1" 200 None
2025-03-25 16:24:01 api-1            | 2025-03-25 16:24:01.493 DEBUG [Dummy-1492] [based_generate_task_pipeline.py:45] - error: Run failed: [vertex_ai] Error: PluginInvokeError: {"args":{"description":"[models] Error: type object 'Part' has no attribute 'from_text'"},"error_type":"InvokeError","message":"[models] Error: type object 'Part' has no attribute 'from_text'"}
2025-03-25 16:24:01 nginx-1          | 192.168.65.1 - - [25/Mar/2025:16:24:01 +0000] "POST /console/api/apps/c83ea2c1-4c1a-421f-bb07-8b5845c11169/advanced-chat/workflows/draft/run HTTP/1.1" 200 11752 "http://localhost/app/c83ea2c1-4c1a-421f-bb07-8b5845c11169/workflow" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36" "-"
```
@dosu how do I downgrade this provider to `0.0.6` as above?

**Comment by xiaobinsheng001** [comment]
I'm having the same issue on a self-hosted instance. I cannot even configure the plugin. The version is 1.1.3 
error：AttributeError: module 'google.cloud.aiplatform_v1' has no attribute 'GenerativeModel'

**Comment by Sanuki-073** [comment]
I discovered that AgentBlock's agentic strategy encounters an error when using function calling, but works without error with ReAct in version 0.0.7.

**Comment by ytjhai** [comment]
I started seeing this after upgrading from 0.15.3 to 1.1.x, will likely have to downgrade back to 0.15.5 because of this issue. Makes Vertex AI unusable

**Comment by fdb02983rhy** [comment]
FYI
- https://github.com/langgenius/dify-official-plugins/pull/651

**Comment by david-sabata** [comment]
Still broken for me. Self-hosted, Dify 1.2.0, plugin 0.0.9., testing on agent.

None of the Gemini models work. Claude 3.5. Sonnect v2 works fine

```
[vertex_ai] Error: PluginInvokeError: {"args":{"description":"[models] Error: module 'vertexai.generative_models' has no attribute 'Schema'"},"error_type":"InvokeError","message":"[models] Error: module 'vertexai.generative_models' has no attribute 'Schema'"}
```

**Comment by Ken-Mok** [comment]
have the same issue, Self-hosted, Dify 1.1.3, plugin 0.0.9

> Still broken for me. Self-hosted, Dify 1.2.0, plugin 0.0.9. . **This is for agent; simple chat works fone.**
> 
> None of the Gemini models work. Claude 3.5. Sonnect v2 works fine
> 
> ```
> [vertex_ai] Error: PluginInvokeError: {"args":{"description":"[models] Error: module 'vertexai.generative_models' has no attribute 'Schema'"},"error_type":"InvokeError","message":"[models] Error: module 'vertexai.generative_models' has no attribute 'Schema'"}
> ```

**Comment by dpleus** [comment]
Same here, using Cloud. Really blocking some of our projects.

**Comment by t-ikeda-mm** [comment]
Even with the latest Vertex AI plugin (v0.0.14), Dify 1.3.1 . I’m still running into errors and the newest models don’t appear. Is anyone actually able to get it working?

**Comment by crazywoola** [comment]
Can you paste the error messages here?

**Comment by jortegac** [comment]
I'm using self-hosted with 1.2.0.

VertexAI plugin 0.0.14 still cannot use tools. I get the error

```
[vertex_ai] Error: PluginInvokeError: {"args":{"description":"[models] Error: module 'vertexai.generative_models' has no attribute 'Schema'"},"error_type":"InvokeError","message":"[models] Error: module 'vertexai.generative_models' has no attribute 'Schema'"}
```

**Comment by t-ikeda-mm** [comment]
@crazywoola 
I'm very satisfied with the excellent features of the community edition.
Although I'm mainly using Azure OpenAI and thus not directly affected, I would still like to be able to use Gemini if possible.

I've consulted several times about the plugin error with VertexAI, but it seems that the issue might not be with VertexAI itself.
Rather, I suspect that updates to the plugin are not being properly reflected in the configuration database.

Even after updating the VertexAI plugin to the latest version 0.0.14, the model list doesn't get updated, and models like Gemini 2.5 are not displayed.
It seems like this configuration update issue is happening only in my environment.

My setup is hosted on AWS EC2, but the PostgreDB is on AWS RDS rather than directly on EC2.
Currently, my Dify version is 1.3.1, but the original database was created back when the version was below 0.15.0 and has been updated repeatedly since then.
I suspect that this update history might be affecting the behavior.

I have already aligned the app/.env and web/.env.local files with the latest versions.

I’m considering starting completely fresh by rebuilding everything from the database up, using the latest version.
If that resolves the issue, then it’s likely not a problem with the plugin itself — and I’ll report back accordingly.
![Image](https://github.com/user-attachments/assets/5309a2d1-cf0b-4996-97ed-ccc9cd6d7fa4)

Here is the error I'm encountering: if I assign any tool to an agent using Gemini and send a request, I receive an error like the one below.

![Image](https://github.com/user-attachments/assets/998cff01-17d7-460c-a85b-31b0cf0a11f6)

I sincerely appreciate this wonderful product.

reference Issue #12545
https://github.com/langgenius/dify/issues/12545

**Comment by fdb02983rhy** [comment]
> @crazywoola 
> I'm very satisfied with the excellent features of the community edition.
> Although I'm mainly using Azure OpenAI and thus not directly affected, I would still like to be able to use Gemini if possible.
> 
> I've consulted several times about the plugin error with VertexAI, but it seems that the issue might not be with VertexAI itself.
> Rather, I suspect that updates to the plugin are not being properly reflected in the configuration database.
> 
> Even after updating the VertexAI plugin to the latest version 0.0.14, the model list doesn't get updated, and models like Gemini 2.5 are not displayed.
> It seems like this configuration update issue is happening only in my environment.
> 
> My setup is hosted on AWS EC2, but the PostgreDB is on AWS RDS rather than directly on EC2.
> Currently, my Dify version is 1.3.1, but the original database was created back when the version was below 0.15.0 and has been updated repeatedly since then.
> I suspect that this update history might be affecting the behavior.
> 
> I have already aligned the app/.env and web/.env.local files with the latest versions.
> 
> I’m considering starting completely fresh by rebuilding everything from the database up, using the latest version.
> If that resolves the issue, then it’s likely not a problem with the plugin itself — and I’ll report back accordingly.
> ![Image](https://github.com/user-attachments/assets/5309a2d1-cf0b-4996-97ed-ccc9cd6d7fa4)
> 
> Here is the error I'm encountering: if I assign any tool to an agent using Gemini and send a request, I receive an error like the one below.
> 
> ![Image](https://github.com/user-attachments/assets/998cff01-17d7-460c-a85b-31b0cf0a11f6)
> 
> I sincerely appreciate this wonderful product.
> 
> reference Issue #12545
> https://github.com/langgenius/dify/issues/12545

Its a known issue. The plugin became buggy since a couples of versions ago. I was trying to reconstruct the code but got overload error frequently then I decided to stop.
https://github.com/langgenius/dify-official-plugins/pull/726

**Comment by t-ikeda-mm** [comment]
Finally, Dify ver 1.4.1 and vertexAI plugin 0.0.18 , I find this error completely solved! 
Thank you very much!

**Comment by ytnobody** [comment]
Today I encountered similar issue with Dify 1.2.0 and Vertex AI Plugin 0.0.19. And I downgraded Vertex AI Plugin as 0.0.16, then I got dify works well.
