### ISSUE TITLE
Error processing trace tasks

### ISSUE THREAD

**Issue by IthacaDream** [langgenius/dify#23166]
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.7.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

I run into an error when tracing data.
I believe this was introduced by PR #23089 
```
Error processing trace tasks
Traceback (most recent call last):
  File "/home/x/dify/api/core/ops/ops_trace_manager.py", line 870, in run
    self.send_to_celery(tasks)
  File "/home/x/dify/api/core/ops/ops_trace_manager.py", line 888, in send_to_celery
    trace_info = task.execute()
                 ^^^^^^^^^^^^^^
  File "/home/x/dify/api/core/ops/ops_trace_manager.py", line 433, in execute
    return self.preprocess()
           ^^^^^^^^^^^^^^^^^
  File "/home/x/dify/api/core/ops/ops_trace_manager.py", line 459, in preprocess
    return preprocess_map.get(self.trace_type, lambda: None)()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/dify/api/core/ops/ops_trace_manager.py", line 451, in <lambda>
    TraceTaskName.TOOL_TRACE: lambda: self.tool_trace(
                                      ^^^^^^^^^^^^^^^^
  File "/home/x/dify/api/core/ops/ops_trace_manager.py", line 780, in tool_trace
    trace_id=self.trace_id,
             ^^^^^^^^^^^^^
AttributeError: 'TraceTask' object has no attribute 'trace_id'
```

### ✔️ Expected Behavior

it should be able to trace data correctly.

### ❌ Actual Behavior

```
2025-07-30 16:22:15|47941|ops_trace_manager.py:872|ERROR|Error processing trace tasks
Traceback (most recent call last):
  File "/home/will/work/dify/api/core/ops/ops_trace_manager.py", line 870, in run
    self.send_to_celery(tasks)
  File "/home/will/work/dify/api/core/ops/ops_trace_manager.py", line 888, in send_to_celery
    trace_info = task.execute()
                 ^^^^^^^^^^^^^^
  File "/home/will/work/dify/api/core/ops/ops_trace_manager.py", line 433, in execute
    return self.preprocess()
           ^^^^^^^^^^^^^^^^^
  File "/home/will/work/dify/api/core/ops/ops_trace_manager.py", line 459, in preprocess
    return preprocess_map.get(self.trace_type, lambda: None)()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/will/work/dify/api/core/ops/ops_trace_manager.py", line 451, in <lambda>
    TraceTaskName.TOOL_TRACE: lambda: self.tool_trace(
                                      ^^^^^^^^^^^^^^^^
  File "/home/will/work/dify/api/core/ops/ops_trace_manager.py", line 780, in tool_trace
    trace_id=self.trace_id,
             ^^^^^^^^^^^^^
AttributeError: 'TraceTask' object has no attribute 'trace_id'
```
