### ISSUE TITLE
Tools - ComfyUI workflow  has error  in Chatbot 

### ISSUE THREAD

**Issue by szkane** [langgenius/dify#12356]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I updated dify to 0.14.2  my Chatbot  got an error msg below. It's worked on previous version.

```
Run failed: Failed to invoke tool: File.init() got an unexpected keyword argument 'dify_model_identity'
```
![image](https://github.com/user-attachments/assets/da671184-e816-4b7d-b3b1-1a621690fd8b)

I have thoroughly reviewed the tools within the ComfyUI workflow for standalone (custom workflow). It does not display any errors; however, it does indicate a chatbot issue.
![image](https://github.com/user-attachments/assets/f10e5f92-2490-472c-8255-14abfd88b568)

### ✔️ Expected Behavior

Chatbot will not output error.

### ❌ Actual Behavior

output error on chatbot workflow

```
Run failed: Failed to invoke tool: File.init() got an unexpected keyword argument 'dify_model_identity'
```

**Comment by hjlarry** [comment]
I think this has been fixed on https://github.com/langgenius/dify/pull/12061
