### ISSUE TITLE
[Agent] Tool invoke error when calling workflow through agent: 'str' object has no attribute 'type'

### ISSUE THREAD

**Issue by 1099446868** [langgenius/dify#21227]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.4.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

**Describe the bug**
When attempting to use an agent to call a workflow tool in Chatflow, I'm encountering a type attribute error despite the tool executing successfully. The workflow tool works correctly when called directly, but when invoked through the agent, it returns the error: `'str' object has no attribute 'type'`.

**To Reproduce**
1. Set up a workflow tool (DataSearchToolV3) that can be successfully called directly
2. Configure an agent to invoke the same workflow tool
3. Trigger the agent with a query requiring tool invocation
4. Observe the error response from the agent

**Expected behavior**
The agent should successfully invoke the workflow tool and return the processed results without type attribute errors.

**Actual behavior**
While the workflow tool executes successfully (confirmed by examining the tool's logs showing correct data returned), the agent returns this error:
```json
{
  "output": {
    "tool_call_id": "call_0_8315cb8d-c0de-4139-8c85-a23cea511cfa",
    "tool_call_input": {
      "com_keyid": "97445420317279291",
      "emp_duty": "060",
      "emp_keyid": "97445420317279913",
      "has_health_document": "yes",
      "public_data": "ebacb1e6ea42e2081b53e13d4b3fc556",
      "query": "Analyze the customer's health condition and provide a nursing plan",
      "question_type": 1,
      "root_id": "97445420317279291",
      "server_sign": "3002.97445420317279291"
    },
    "tool_call_name": "DataSearchToolV3",
    "tool_response": "tool invoke error: 'str' object has no attribute 'type'"
  }
}
```

**Additional context**
- Dify version: 1.4.2
- The workflow tool's logs show successful execution and correct data return
- Agent logs show the type attribute error preventing proper result handling
- This appears to be an integration issue between the agent and workflow tool components

**Comment by 1099446868** [comment]
[@dosu](https://go.dosu.dev/dosubot) @dosu Are you saying that I need to modify the code of dify that I deployed? This is the end node of my workflow. How can I make my return a ToolInvoke Message object？
![Image](https://github.com/user-attachments/assets/0697c160-7b1c-4971-966c-acd530f277be)

**Comment by 1099446868** [comment]
[@dosu](https://go.dosu.dev/dosubot) @dosu It is possible that there is an issue with the Dify Agent Policy plugin. When I upgraded to 0.0.16 today, this problem occurred. However, when I downgraded to 0.0.15, there was no problem

![Image](https://github.com/user-attachments/assets/0c340868-01a3-4923-86fc-4a49ff62a6f2)
