### ISSUE TITLE
When calling the published workflow via the API, an issue occurred during the speech-to-text processing after retrieving the file from OSS by URL.

### ISSUE THREAD

**Issue by wjyrun** [langgenius/dify#25253]
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.7.1  1.8.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. We called the workflow via API  1.1.0 version, it did work
2. After we upgraded to version 1.71, we encountered an issue where using an OSS audio file as a parameter to the speech-to-text tool caused it to malfunction.

**error log:**
```2025-09-05 07:33:18.251 ERROR [Thread-8 (_generate_worker)] [graph_engine.py:846] - Node 语音转文字 run failed
Traceback (most recent call last):
  File "/app/api/core/workflow/graph_engine/graph_engine.py", line 647, in _run_node
    for event in event_stream:
                 ^^^^^^^^^^^^
  File "/app/api/core/workflow/nodes/base/node.py", line 78, in run
    yield from result
  File "/app/api/core/workflow/nodes/tool/tool_node.py", line 136, in _run
    yield from self._transform_message(
  File "/app/api/core/workflow/nodes/tool/tool_node.py", line 254, in _transform_message
    for message in message_stream:
                   ^^^^^^^^^^^^^^
  File "/app/api/core/tools/utils/message_transformer.py", line 68, in transform_tool_invoke_messages
    for message in messages:
                   ^^^^^^^^
  File "/app/api/core/callback_handler/workflow_tool_callback_handler.py", line 21, in on_tool_execution
    for tool_output in tool_outputs:
                       ^^^^^^^^^^^^
  File "/app/api/core/tools/builtin_tool/providers/audio/tools/asr.py", line 31, in _invoke
    provider, model = tool_parameters.get("model").split("#")  # type: ignore
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```

### ✔️ Expected Behavior

using the API to call the published workflow normally

### ❌ Actual Behavior

it didn't work

**Comment by wjyrun** [comment]
@dosu Thank you for your reply. Initially, we had already configured the STT model in the system model settings and specified the Model in the workflow orchestration page. The issue of the model not being found occurred after invoking the workflow via the API. So, I now need your further assistance.

<img width="999" height="541" alt="Image" src="https://github.com/user-attachments/assets/2d3ded05-f9c0-4477-bded-3b781d60bb1e" />

<img width="1008" height="544" alt="Image" src="https://github.com/user-attachments/assets/8d6cf3aa-7fad-4958-a085-88da7aa0f00f" />

**Comment by crazywoola** [comment]
What does your url look like?

**Comment by wjyrun** [comment]
@dosu This is a simple example DSL file. Please give me an example of the API request payload structure, including the model parameter.

[语音转文字.yml](https://github.com/user-attachments/files/22169390/default.yml)

**Comment by wjyrun** [comment]
> What does your url look like?

@crazywoola  https://sss***s*.oss-cn-shanghai.aliyuncs.com/RecordingFile/202509/03/20250903012*******.wav?OSSAccessKeyId=*******&Expires=1756953976&Signature=K%2Ft6rtWG1******

**Comment by wjyrun** [comment]
@dosu We attempted the approach you suggested but encountered another issue. However, we eventually identified the root cause: after upgrading Dify from version 1.1.0 to 1.71, we had not clicked the "Publish" button. Today, after clicking it, the API call worked successfully. I will close the issue. 
Thanks
