### PR TITLE
fix: mypy checks violation in AzureBlobStorage

### LINKED ISSUE #13216: mypy checks violation in AzureBlobStorage
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

master

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

- the violation in mypy checks:
```
extensions/storage/azure_blob_storage.py:25: error: Incompatible types in assignment (expression has type "None", variable has type "DefaultAzureCredential")  [assignment]
extensions/storage/azure_blob_storage.py:67: error: Argument "account_url" to "BlobServiceClient" has incompatible type "str | None"; expected "str"  [arg-type]
Found 2 errors in 1 file (checked 952 source files)
```

### ✔️ Expected Behavior

_No response_

### ❌ Actual Behavior

_No response_

### PR DESCRIPTION
**Pull request by bowenliang123**
# Summary
- to fix #13216 bug introduced in #13216
- to fix the violation in mypy checks:
```
extensions/storage/azure_blob_storage.py:25: error: Incompatible types in assignment (expression has type "None", variable has type "DefaultAzureCredential")  [assignment]
extensions/storage/azure_blob_storage.py:67: error: Argument "account_url" to "BlobServiceClient" has incompatible type "str | None"; expected "str"  [arg-type]
Found 2 errors in 1 file (checked 952 source files)
```

> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.

# Screenshots

| Before | After |
|--------|-------|
| ...    | ...   |

# Checklist

> [!IMPORTANT]  
> Please review the checklist below before submitting your pull request.

- [ ] This change requires a documentation update, included: [Dify Document](https://github.com/langgenius/dify-docs)
- [x] I understand that this PR may be closed in case there was no previous discussion or issues. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [x] I've updated the documentation accordingly.
- [x] I ran `dev/reformat`(backend) and `cd web && npx lint-staged`(frontend) to appease the lint gods

### CODE REVIEW

**Comment by bowenliang123** [comment]
cc @crazywoola

**Review by crazywoola — APPROVED** [review]
